apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app: quarkuscoffeeshop-debezium-container
  name: quarkuscoffeeshop-debezium-container-pipeline
spec:
  params:
    - default: quay-quay-quay.router-default.apps.rad-two.rhpds.aws.uc2.io/quarkuscoffeeshop/quarkuscoffeeshop-debezium-container
      name: QUAY_REPO
      type: string
    - default: 'https://github.com/GuilhermeCamposo/quarkuscoffeeshop-debezium-container'
      name: POSTGRESQL_REPO
      type: string
    - default: main
      description: Select Branch
      name: BRANCH_NAME
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.POSTGRESQL_REPO)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.BRANCH_NAME)
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-push-image
      params:
        - name: BASE_IMAGE
          value: centos/postgresql-96-centos7:latest
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: $(params.QUAY_REPO)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: build-from-redhat
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
