kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: quarkuscoffeeshop-debezium-container-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
